name: Deployment

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      TARGETS:
        required: true
        type: string
    secrets:
      PASS:
        required: true 
   
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:  ${{ inputs.ENV }}
    
    steps:      
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
         #name: dist
         path: artifactNew
       #  if-no-files-found: error 

      - name: Deploy ${{ inputs.ENV }}
        run: | 
             echo "------------[${{ inputs.ENV }} -  [${{ secrets.PASS }}] ${{ inputs.TARGETS }} ]---------------"
             echo "------------  Deployment is done -------- THE END -------------------"



