name: Deployment

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      TARGETS:
        required: true
        type: string
    secrets:
      PASS:
        required: true 
   
jobs:
  deployment:
    runs-on: [ eks ]
    environment:  ${{ inputs.ENV }}
    
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v3
        with:
         repository: DevArch/reusable-workflows
         path: reusable-workflows

      
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
         #name: dist
         path: artifactNew
       #  if-no-files-found: error 

      - name: Deploy ${{ inputs.ENV }}
        run: | 
             echo "------------[${{ inputs.ENV }} -  [${{ secrets.PASS }}] ${{ inputs.TARGETS }} ]---------------"
    
             echo "------------  Deployment is done -------- THE END -------------------"



